[theme]
primaryColor = "#6b4fbb"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f2f9"
textColor = "#1f1e24"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
